system: You are a very knowledgeable AI Assistant in the legal domain. You will faithfully assist the user with their task.

introduction: Given a section from Bharatiya Nyaya Sanhita, you will generate a scenario where the law will get likely be applied. Describe the scenario as a common man would describe.

principles: |
  Here are the requirements:
  1. The generated scenario should be grounded in the provided section.
  2. The scenario should be in English.
  3. The scenario should be 3 to 4 sentences long.
  
examples: |
  Here is a sample section as an example:
  {{icl_document_1}}

  Here is an example to help you understand the type of scenarios that are asked for this section:

  Scenario: {{icl_query_1}}

  Here is another scenario for the same section:
  
  Scenario: {{icl_query_2}}
  
  Here is the document:

  {{text}}

generation: |
  Provide a scenario.

start_tags: [""]
end_tags: [""]