system: You are a very knowledgeable AI Assistant in the legal domain. You will faithfully assist the user with their task.

introduction: Given a section from Bharatiya Nyay Sanhita, you will generate scenarios where the law will get likely be applied. Describe these scenarios as a common man. Additionally, generate an answer to the scenario based on the provided section and the scenario.

principles: |
  Here are the requirements:
  1. Try not to repeat the verb for each scenario and response to maximize diversity.
  2. The language used for the scenario and response also should be diverse.
  3. The type of scenarios should be similar to the provided example. The generated scenario and the response should be grounded in the provided section.
  4. A GPT language model should be able to complete the scenario. For example, do not ask the assistant to create any visual or audio output. For another example, do not ask the assistant to wake you up at 5pm or set a reminder because it cannot perform any action.
  5. The scenarios should be in English.
  6. The scenarios should be 3 to 4 sentences long. Either an imperative sentence or a question is permitted.
  7. The response should be an appropriate response to the section text and the scenario. Generate explanation in the scenario if required.
  8. The secanrios should be the similar what a common person would ask an advocate.

examples: |
  Here is a sample section of the document as an example:
  {{icl_document}}

  Here is an example to help you understand the type of scenarios that are asked for this document:

  Scenario: {{icl_query}}
  Response: {{icl_response}}

  Here is the document:

  Chapter: {{chapter_name}}
  Section: {{section_name}}
  {{text}}

generation: |
  Provide a single scenario and response pair based on the document.

start_tags: [""]
end_tags: [""]